# Copyright 2022 leorize <leorize+oss@disroot.org>
#
# SPDX-License-Identifier: CC0-1.0

name: Setup Nimskull
description: Setup a Nimskull development environment
branding:
  color: blue
  icon: code

inputs:
  token:
    description: The Github token to retrieve data from nimskull repository
    required: true
    default: ${{ github.token }}
  nimskull-version:
    description:
      The semver specification for nimskull version to use. Defaults to any
      version
    required: true
    default: "*"
  check-latest:
    description:
      Whether to always check for the latest version satisfying the given spec.
      Defaults to true as nimskull is still in pre-alpha status.
    default: "true"
outputs:
  path:
    description: The resulting installation location
  bin-path:
    description: Where binaries were installed
  nimskull-version:
    description: The installed nimskull version
  nimskull-commit:
    description: The commit of the compiler

runs:
  using: "node20"
  main: "dist/index.js"
